# Docs for Azure Web Apps Deploy Action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read      
      actions: read
      checks: write

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v5

      # Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x' # Adjust if your project targets .NET 8 or lower

      # Restore dependencies (specific project path)
      - name: Restore dependencies
        run: dotnet restore 

      # Build the API project in Release mode
      - name: Build project
        run: dotnet build --no-restore --configuration Release

      # Run unit tests with report & coverage
      - name: Run unit tests
        run: |
            dotnet test --configuration Release --no-build --no-restore --logger "trx;LogFileName=unit_test_results.trx" --results-directory ./TestResults

      # Upload test results as artifact
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults

      # Publish test summary to GitHub Actions UI
      - name: Publish test report summary
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Unit Test Results
          path: ./TestResults/unit_test_results.trx
          reporter: dotnet-trx
          fail-on-error: true

      # Publish the compiled output to the /myapp folder
      - name: Publish project
        run: dotnet publish ./Riatix.Azure.NLToSQLEngine/Riatix.Azure.NLToSQLEngine.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      # Upload the published output as an artifact for deployment
      - name: Upload published artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download the published output
      - name: Download published artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
          path: .

      # Deploy to Azure App Service
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'rixnl2sqlapi' # Your App Service name
          slot-name: 'Production' # Optional; remove if not using slots
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .